builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - id: cwf
  - ids:
    - cwf
  - image_templates:
    - "noobcollective/cwf-server:latest"
    - "noobcollective/cwf-server:{{ .Tag }}"
