builds:
- env: [CGO_ENABLED=0]
  goos:
  - linux
  goarch:
  - amd64
dockers:
  - id: cwf
  - ids:
    - cwf
  - image_templates:
    - "noobcollective/cwf:latest"
    - "noobcollective/cwf:{{ .Tag }}"
