[server]
motherShipIP = '127.0.0.1'
motherShipPort = '8787'
motherShipSSL = true

[[server.accounts]]
userName = 'iCulture'
nonce = '6683f778-1b51-4699-bca3-75def7da0892'
registered = false

[[server.accounts]]
userName = 'DrinoSan'
nonce = 'eee3c40f-8b04-486f-8706-497458b6ae27'
registered = false
